name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: npm install
      run: npm install

    - name: npm jquery
      run: npm i @types/jquery

    - name: npm materialize
      run: npm install --save @types/materialize-css

    - name: Build with dotnet
      run: dotnet build --configuration Release
    
